version: 2.1
jobs:
# Exercise: Config and Deployment
  configure_infrastructure: 
      docker:
        - image: python:3.7-alpine3.15
      steps:
        - checkout
        - add_ssh_keys:
                # You can get this ID in the section where you registered the SSH Key
                fingerprints: ["91:97:d3:35:28:fd:ef:50:ea:b0:f0:ae:72:09:d4:c6"] 
        - run:
            name: Install Ansible
            command: apk add --update ansible
              # Install Ansible
        - run:
            name: Run Playbook and Configure server
            command: ansible-playbook -i inventory playbook.yml

workflows:
  myWorkflow:
    jobs:
      - configure_infrastructure
